version: "3"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  calculator:
    build: ./calculator
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: calculator